n=int(input('Digite um número: '))
print(type(n))
m=float(input('Digite um número quebrado: '))
print(type(m))
o=bool(input('Digite um verdadeiro ou falso: '))
print(type(o))
p=bool(input('Digite algo: '))
print(type(p))
q=str(input('Digite uma palavra: '))
print(type(q))